import os
import sys
from dotenv import load_dotenv

# 0. Load .env immediately for tokens
load_dotenv()

# 1. IMMEDIATE ENVIRONMENT SETUP (Must happen before any ML imports)
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../"))
models_dir = os.path.join(project_root, "models")
os.makedirs(models_dir, exist_ok=True)

# Torch Hub models (Silero VAD)
os.environ["TORCH_HOME"] = os.path.join(models_dir, "torch")
# HuggingFace / Transformers / Faster-Whisper
os.environ["HF_HOME"] = os.path.join(models_dir, "huggingface")
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"
# General cache
os.environ["XDG_CACHE_HOME"] = os.path.join(models_dir, "cache")

# Add site-packages to PATH for CUDA DLLs (Windows specific)
import site
for path in site.getsitepackages():
    bin_path = os.path.join(path, "nvidia", "cublas", "bin")
    if os.path.exists(bin_path):
        os.environ["PATH"] += os.pathsep + bin_path
    bin_path = os.path.join(path, "nvidia", "cudnn", "bin")
    if os.path.exists(bin_path):
        os.environ["PATH"] += os.pathsep + bin_path

# Add src to path
sys.path.append(project_root)

import asyncio
import numpy as np
import soundfile as sf
from src.providers.tts.pocket_tts import PocketTTSProvider

async def test_tts():
    print(f"Models directory: {models_dir}")
    print("Initializing PocketTTSProvider...")
    try:
        provider = PocketTTSProvider(voice="alba")
        print(f"Model sample rate: {provider.sample_rate}")
        
        print("Synthesizing text...")
        
        async def text_gen():
            yield "Hello, this is a local real-time voice generated by Pocket TTS. "
            yield "It fits in my pocket and runs on my CPU."

        audio_chunks = []
        start_time = asyncio.get_event_loop().time()
        async for chunk in provider.synthesize_stream(text_gen()):
            if not audio_chunks:
                print(f"Time to first audio chunk: {asyncio.get_event_loop().time() - start_time:.2f}s")
            print(f"Received audio chunk of shape: {chunk.shape}")
            audio_chunks.append(chunk)

        if audio_chunks:
            full_audio = np.concatenate(audio_chunks)
            output_file = "pocket_test_output.wav"
            sf.write(output_file, full_audio, provider.sample_rate)
            print(f"Success! Audio saved to {output_file}")
        else:
            print("Error: No audio generated.")

    except Exception as e:
        print(f"TTS Test Failed: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(test_tts())
